on:
  push:
  workflow_dispatch:
    inputs:
      fail:
        type: boolean
jobs:
  assert:
    if: ${{ inputs.fail }}
    runs-on: ubuntu-latest
    continue-on-error: ${{ github && 'failure' }}
    steps:
    - run: exit 1
